name: Push to Development Docs
on: push
#  push:
#    branches:
#      - master
#    paths:
#      - 'docs/*'

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install virtualenv
        run: sudo pip3 install virtualenv
      - name: Build documentation
        run: |
          export PATH=/usr/local/bin:$PATH
          ./docs/build.sh -r development -v development
      - name: Clone titan-data.github.io
        run: |
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/eschrock/titan-data.github.io.git
          cd ./titan-data.github.io && git log -1
      - name: Configure git
        run: |
          cd ./titan-data.github.io
          git config user.name "titan-docs"
          git config user.email "titan-docs@users.noreply.github.com"
      - name: Publish docs
        run: ./docs/publish.sh -v development ./titan-data.github.io
