name: Push to Development Docs
on: push
#  push:
#    branches:
#      - master
#    paths:
#      - 'docs/*'

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-18.04
    steps:
      - name: Clone titan-data.github.io
        run: |
          HEADER=$(echo -n "${{ secrets.GITHUB_TOKEN }}" | base64)
          echo $HEADER
          git -c http.extraheader="AUTHORIZATION: basic $HEADER" clone git@github.com:eschrock/titan-data.github.io
      - uses: actions/checkout@v1
      - name: Install virtualenv
        run: sudo pip3 install virtualenv
      - name: Build documentation
        run: |
          export PATH=/usr/local/bin:$PATH
          ./docs/build.sh -r development -v development
      - name: Publish docs
        run: ./docs/publish.sh -v development ./titan-data.github.io
