name: Push to Development Docs
on: push
#  push:
#    branches:
#      - master
#    paths:
#      - 'docs/*'

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build documentation
        run: ./docs/build.sh -r development -v development
      - name: Clone titan-data.github.io
        run: git clone git@github.com:eschrock/titan-data.github.io
      - name: Publish docs
        run: ./docs/publish.sh -v development ./titan-data.github.io
